In [52]:
import numpy as np
a = np.array(85, ndmin = 0)
b = np.array([20, 21, 22])
c = np.array([[30, 31, 32],[33,34,35]])
d = np.array([[[400, 401, 402], [403, 404, 405], [406, 407, 408]]])

print("*0D*:", a , "Dim:" , a.ndim)
print("\n *1D*:", b , "Dim:" , b.ndim)
print("\n *2D*:", c , "Dim:" , c.ndim)
print("\n *3D*:", d , "Dim:" , d.ndim)

*0D*: 85 Dim: 0

 *1D*: [20 21 22] Dim: 1

 *2D*: [[30 31 32]
 [33 34 35]] Dim: 2

 *3D*: [[[400 401 402]
  [403 404 405]
  [406 407 408]]] Dim: 3
