In [1]:
import numpy as np
slise = np.array(range(1,101)).reshape(10,10)

In [24]:
slise

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [26]:
slise[1:9,1:9]

array([[12, 13, 14, 15, 16, 17, 18, 19],
       [22, 23, 24, 25, 26, 27, 28, 29],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47, 48, 49],
       [52, 53, 54, 55, 56, 57, 58, 59],
       [62, 63, 64, 65, 66, 67, 68, 69],
       [72, 73, 74, 75, 76, 77, 78, 79],
       [82, 83, 84, 85, 86, 87, 88, 89]])

In [27]:
slise[2:8,2:8]

array([[23, 24, 25, 26, 27, 28],
       [33, 34, 35, 36, 37, 38],
       [43, 44, 45, 46, 47, 48],
       [53, 54, 55, 56, 57, 58],
       [63, 64, 65, 66, 67, 68],
       [73, 74, 75, 76, 77, 78]])

In [28]:
slise[3:7,3:7]

array([[34, 35, 36, 37],
       [44, 45, 46, 47],
       [54, 55, 56, 57],
       [64, 65, 66, 67]])

In [29]:
slise[4:6,4:6]

array([[45, 46],
       [55, 56]])

In [11]:
slise[0:2,0:2]

array([[ 1,  2],
       [11, 12]])

In [12]:
slise[0:2,2:4]

array([[ 3,  4],
       [13, 14]])

In [30]:
slise[0:2,4:6]

array([[ 5,  6],
       [15, 16]])

In [31]:
slise[0:2,6:8]

array([[ 7,  8],
       [17, 18]])

In [62]:
slise[0:2,8:]

array([[ 9, 10],
       [19, 20]])

In [14]:
slise[2:4,0:2]

array([[21, 22],
       [31, 32]])

In [15]:
slise[2:4,2:4]

array([[23, 24],
       [33, 34]])

In [35]:
slise[2:4,4:6]

array([[25, 26],
       [35, 36]])

In [36]:
slise[2:4,6:8]

array([[27, 28],
       [37, 38]])

In [61]:
slise[2:4,8:]

array([[29, 30],
       [39, 40]])

In [44]:
slise[4:6,0:2]

array([[41, 42],
       [51, 52]])

In [45]:
slise[4:6,2:4]

array([[43, 44],
       [53, 54]])

In [46]:
slise[4:6,4:6]

array([[45, 46],
       [55, 56]])

In [47]:
slise[4:6,6:8]

array([[47, 48],
       [57, 58]])

In [60]:
slise[4:6,8:]

array([[49, 50],
       [59, 60]])

In [49]:
slise[6:8,0:2]

array([[61, 62],
       [71, 72]])

In [51]:
slise[6:8,2:4]

array([[63, 64],
       [73, 74]])

In [50]:
slise[6:8,4:6]

array([[65, 66],
       [75, 76]])

In [52]:
slise[6:8,6:8]

array([[67, 68],
       [77, 78]])

In [59]:
slise[6:8,8:]

array([[69, 70],
       [79, 80]])

In [54]:
slise[8:,0:2]

array([[81, 82],
       [91, 92]])

In [55]:
slise[8:,2:4]

array([[83, 84],
       [93, 94]])

In [56]:
slise[8:,4:6]

array([[85, 86],
       [95, 96]])

In [57]:
slise[8:,6:8]

array([[87, 88],
       [97, 98]])

In [58]:
slise[8:,8:]

array([[ 89,  90],
       [ 99, 100]])