In [50]:
import numpy as np
slise = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24],[25,26,27,28,29,30],[31,32,33,34,35,36]])

In [39]:
slise

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [40]:
slise[0:2,0:2]

array([[1, 2],
       [7, 8]])

In [41]:
slise[0:2,2:4]

array([[ 3,  4],
       [ 9, 10]])

In [42]:
slise[0:2,4:]

array([[ 5,  6],
       [11, 12]])

In [44]:
slise[2:4,0:2]

array([[13, 14],
       [19, 20]])

In [45]:
slise[2:4,2:4]

array([[15, 16],
       [21, 22]])

In [46]:
slise[2:4,4:]

array([[17, 18],
       [23, 24]])

In [47]:
slise[4:,0:2]

array([[25, 26],
       [31, 32]])

In [48]:
slise[4:,2:4]

array([[27, 28],
       [33, 34]])

In [49]:
slise[4:,4:]

array([[29, 30],
       [35, 36]])

In [55]:
slise[1:3,1:3]

array([[ 8,  9],
       [14, 15]])

In [56]:
slise[1:3,3:5]

array([[10, 11],
       [16, 17]])

In [57]:
slise[3:5,1:3]

array([[20, 21],
       [26, 27]])

In [58]:
slise[3:5,3:5]

array([[22, 23],
       [28, 29]])